# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      run: |
        docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
  
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag d1243/docker_1:latest:$(date +%s)
    - name: Docker push
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/docker_1
